### ISSUE TITLE
[Demo] ERROR ~ Error executing process > 'minimap_pipeline:makeReport (1)'

### ISSUE THREAD

**Issue by nikelau** [epi2me-labs/wf-16s#13]
### Operating System

Windows 11

### Workflow Version

1.1.2

### Workflow Execution

EPI2ME Desktop (Local)

### EPI2ME Version

EPI2ME V5.1.10

### Workflow Execution - CLI Execution Profile

None

### What happened?

To circumvent the no file error, i read the update log and saw that it was probably due to a new feature introduced in 1.1.13, so i decided to roll back to 1.1.12. 
However when trying to run the demo data I encounter this error: AttributeError: 'BokehPlot' object has no attribute 'xAxis'

### Relevant log output

```shell
N E X T F L O W  ~  version 23.04.2
Launching `/mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s/main.nf` [quizzical_poincare] DSL2 - revision: 7338c9bcbe
WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASES
WARN: Found unexpected parameters:
* --client_fields: D:\epi2melabs\instances\wf-16s_01HW288NBDGPPV2J54WATJPV4Q\client_fields.json
- Ignore this warning: params.schema_ignore_params = "client_fields" 
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-16s v1.1.2
--------------------------------------------------------------------------------
Core Nextflow options
  runName              : quizzical_poincare
  containerEngine      : docker
  launchDir            : /mnt/d/epi2melabs/instances/wf-16s_01HW288NBDGPPV2J54WATJPV4Q
  workDir              : /mnt/d/epi2melabs/instances/wf-16s_01HW288NBDGPPV2J54WATJPV4Q/work
  projectDir           : /mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s
  userName             : epi2mewsl
  profile              : standard
  configFiles          : /mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s/nextflow.config, /mnt/d/epi2melabs/instances/wf-16s_01HW288NBDGPPV2J54WATJPV4Q/demo.config
Input Options
  fastq                : /mnt/d/epi2melabs/demo/epi2me-labs/wf-16s/3bbe528be199700c845d12b12b9d02812c332acb/wf-16s-demo/test_data
Reference Options
  store_dir            : /mnt/d/epi2melabs/data
  database_sets        : [ncbi_16s_18s:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_kraken2.tar.gz, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], ncbi_16s_18s_28s_ITS:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS_kraken2.tar.gz, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ref2taxid.ncbi_16s_18s_28s_ITS.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], SILVA_138_1:[database:null]]
Minimap2 Options
  minimap2_by_reference: true
Output Options
  out_dir              : /mnt/d/epi2melabs/instances/wf-16s_01HW288NBDGPPV2J54WATJPV4Q/output
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-16s for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-16s v1.1.2.
--------------------------------------------------------------------------------
Checking inputs.
Searching input for [.fastq, .fastq.gz, .fq, .fq.gz] files.
Minimap2 pipeline.
Preparing databases.
Using default taxonomy database.
Using a default database.
[skipping] Stored process > prepare_databases:download_unpack_taxonomy
[skipping] Stored process > prepare_databases:download_reference_ref2taxid
[d8/9d9b6e] Submitted process > fastcat (1)
[b1/1608b5] Submitted process > minimap_pipeline:run_common:getVersions
[ce/4010b4] Submitted process > minimap_pipeline:run_common:getParams
[a1/3b0a8c] Submitted process > fastcat (3)
[e2/b796d5] Submitted process > fastcat (2)
[b8/56fa5c] Submitted process > minimap_pipeline:minimap (1)
[08/3730f0] Submitted process > minimap_pipeline:output (1)
[e2/806ba6] Submitted process > minimap_pipeline:output (2)
[a1/7ee948] Submitted process > minimap_pipeline:minimap (2)
[2a/1f9050] Submitted process > minimap_pipeline:minimap (3)
[82/fb8340] Submitted process > minimap_pipeline:getAlignmentStats (1)
[5b/66c99c] Submitted process > minimap_pipeline:getAlignmentStats (2)
[39/685f83] Submitted process > minimap_pipeline:getAlignmentStats (3)
[f4/fd51c5] Submitted process > minimap_pipeline:createAbundanceTables
[3d/d2b4b5] Submitted process > minimap_pipeline:output (3)
[77/39e0ba] Submitted process > minimap_pipeline:makeReport (1)
ERROR ~ Error executing process > 'minimap_pipeline:makeReport (1)'
Caused by:
  Process `minimap_pipeline:makeReport (1)` terminated with an error exit status (1)
Command executed:
  workflow-glue report         "wf-16s-report.html"         --workflow_name wf-16s         --versions versions         --params params.json         --read_stats read_stats/*         --lineages lineages         --abundance_table "abundance_table_genus.tsv"         --taxonomic_rank "G"         --pipeline "minimap2"         --abundance_threshold "1"        --n_taxa_barplot "9"        --align_stats alignment_stats
Command exit status:
  1
Command output:
  (empty)
Command error:
  [07:13:22 - matplotlib.font_manager] generated new fontManager
  [07:13:22 - workflow_glue] Starting entrypoint.
  [07:13:23 - workflow_glue.Report    ] Sample barcode01.
  [07:13:23 - EChrtPlotr] Skipping axis label fixing
  [07:13:23 - workflow_glue.Report    ] Sample barcode02.
  [07:13:23 - EChrtPlotr] Skipping axis label fixing
  [07:13:23 - workflow_glue.Report    ] Sample barcode03.
  [07:13:23 - EChrtPlotr] Skipping axis label fixing
  [07:13:23 - workflow_glue.Report    ] rank phylum.
  Traceback (most recent call last):
    File "/mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s/bin/workflow-glue", line 7, in <module>
      cli()
    File "/mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s/wf-metagenomics/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s/wf-metagenomics/bin/workflow_glue/report.py", line 232, in main
      plt.xAxis.axisLabel = dict(rotate=45)
  AttributeError: 'BokehPlot' object has no attribute 'xAxis'
Work dir:
  /mnt/d/epi2melabs/instances/wf-16s_01HW288NBDGPPV2J54WATJPV4Q/work/77/39e0bae83069def05086f89bbc8d84
Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
 -- Check '/mnt/d/epi2melabs/instances/wf-16s_01HW288NBDGPPV2J54WATJPV4Q/nextflow.log' file for details
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by nikelau** [comment]
I tried re-installing the workflow and seems it works now with v1.1.3. 

here is the log:
N E X T F L O W  ~  version 23.04.2
Launching `/mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s/main.nf` [friendly_lichterman] DSL2 - revision: 8363748886
WARN: NEXTFLOW RECURSION IS A PREVIEW FEATURE - SYNTAX AND FUNCTIONALITY CAN CHANGE IN FUTURE RELEASES
WARN: Found unexpected parameters:
* --client_fields: D:\epi2melabs\instances\wf-16s_01HWF4C7M8H4ZJJVBS76V80S1C\client_fields.json
- Ignore this warning: params.schema_ignore_params = "client_fields" 
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-16s v1.1.3
--------------------------------------------------------------------------------
Core Nextflow options
  runName              : friendly_lichterman
  containerEngine      : docker
  launchDir            : /mnt/d/epi2melabs/instances/wf-16s_01HWF4C7M8H4ZJJVBS76V80S1C
  workDir              : /mnt/d/epi2melabs/instances/wf-16s_01HWF4C7M8H4ZJJVBS76V80S1C/work
  projectDir           : /mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s
  userName             : epi2mewsl
  profile              : standard
  configFiles          : /mnt/d/epi2melabs/workflows/epi2me-labs/wf-16s/nextflow.config, /mnt/d/epi2melabs/instances/wf-16s_01HWF4C7M8H4ZJJVBS76V80S1C/demo.config
Input Options
  fastq                : /mnt/d/epi2melabs/demo/epi2me-labs/wf-16s/4a8184a7051ee15baf45371c909b9aac924a3a81/wf-16s-demo/test_data
Reference Options
  store_dir            : /mnt/d/epi2melabs/data
  database_sets        : [ncbi_16s_18s:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_16s_18s.fna, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ncbi_targeted_loci_kraken2.tar.gz, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s/ref2taxid.targloci.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], ncbi_16s_18s_28s_ITS:[reference:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS.fna, database:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ncbi_16s_18s_28s_ITS_kraken2.tar.gz, ref2taxid:https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-metagenomics/ncbi_16s_18s_28s_ITS/ref2taxid.ncbi_16s_18s_28s_ITS.tsv, taxonomy:https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump_archive/taxdmp_2023-01-01.zip], SILVA_138_1:[database:null]]
Minimap2 Options
  minimap2_by_reference: true
Output Options
  out_dir              : /mnt/d/epi2melabs/instances/wf-16s_01HWF4C7M8H4ZJJVBS76V80S1C/output
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-16s for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-16s v1.1.3.
--------------------------------------------------------------------------------
Checking inputs.
Searching input for [.fastq, .fastq.gz, .fq, .fq.gz] files.
Note: Empty files or those files whose reads have been discarded after filtering based on read length and/or read quality will not appear in the report and will be excluded from subsequent analysis.
Minimap2 pipeline.
Preparing databases.
Using default taxonomy database.
Using a default database.
[c7/33feff] Submitted process > prepare_databases:download_reference_ref2taxid
[bb/236da4] Submitted process > minimap_pipeline:run_common:getVersions
[fd/e0d688] Submitted process > minimap_pipeline:run_common:getParams
[0f/3c175b] Submitted process > fastcat (2)
[90/6962f6] Submitted process > prepare_databases:download_unpack_taxonomy
[00/37c499] Submitted process > minimap_pipeline:output_results (1)
[25/a6ce84] Submitted process > fastcat (1)
[f0/a4ff72] Submitted process > fastcat (3)
[d8/2c745e] Submitted process > minimap_pipeline:output_results (2)
[26/14b949] Submitted process > minimap_pipeline:minimap (barcode01)
[63/e8005b] Submitted process > minimap_pipeline:minimap (barcode03)
[92/05a0c4] Submitted process > minimap_pipeline:minimap (barcode02)
[1d/5e3287] Submitted process > minimap_pipeline:getAlignmentStats (barcode03)
[5a/29f22e] Submitted process > minimap_pipeline:getAlignmentStats (barcode01)
[e5/088201] Submitted process > minimap_pipeline:getAlignmentStats (barcode02)
[cc/114ba8] Submitted process > minimap_pipeline:createAbundanceTables
[4a/d9ddb5] Submitted process > minimap_pipeline:output_results (3)
[03/d08983] Submitted process > minimap_pipeline:makeReport (1)
[fb/23cb74] Submitted process > minimap_pipeline:output_results (4)
