### ISSUE TITLE
Error when making report

### ISSUE THREAD

**Issue by yanchunzhang** [epi2me-labs/wf-16s#5]
Hi, I had a problem running the demo data. Please see the error message below. Do you know how to solve this problem?
Thanks,
Yanchun

Error executing process > 'kraken_pipeline:makeReport (1)'

Caused by:
  Process `kraken_pipeline:makeReport (1)` terminated with an error exit status (1)

Command executed:

  workflow-glue report         "wf-16s-report.html"         --workflow_name wf-16s         --versions versions         --params params.json         --read_stats read_stats/*         --lineages lineages         --abundance_table "abundance_table_genus.tsv"         --taxonomic_rank "G"         --pipeline "kraken2"         --abundance_threshold "1"        --n_taxa_barplot "8"

Command exit status:
  1

Command output:
  (empty)

Command error:
  [15:02:34 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/hpc/users/zhangy40/.nextflow/assets/epi2me-labs/wf-16s/bin/workflow-glue", line 7, in <module>
      cli()
    File "/hpc/users/zhangy40/.nextflow/assets/epi2me-labs/wf-16s/wf-metagenomics/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/hpc/users/zhangy40/.nextflow/assets/epi2me-labs/wf-16s/wf-metagenomics/bin/workflow_glue/report.py", line 114, in main
      SeqSummary(args.read_stats)
    File "/hpc/users/zhangy40/schzrnas/softwares/conda/env/nf16s/lib/python3.10/site-packages/ezcharts/components/fastcat.py", line 47, in __init__
      df_all = load_stats(seq_summary, format='fastcat')
    File "/hpc/users/zhangy40/schzrnas/softwares/conda/env/nf16s/lib/python3.10/site-packages/ezcharts/components/fastcat.py", line 337, in load_stats
      if os.path.isdir(stat):
    File "/hpc/users/zhangy40/schzrnas/softwares/conda/env/nf16s/lib/python3.10/genericpath.py", line 42, in isdir
      st = os.stat(s)
  TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

Work dir:
  /sc/arion/projects/schzrnas/zhangy40/intratumor_bacteria/010324_16s/processed/demulti_trim/work/5b/2ac0627b4dd170ec04b2b94b1186b8

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by cjw85** [comment]
Please reopen your issue using the Bug Report Issue template and providing the information requested.
